# Generated by Django 4.0.2 on 2022-03-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_paid_order_delivery_order_dish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
