# Generated by Django 4.0.2 on 2022-03-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_weight',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
