# Generated by Django 4.0.2 on 2022-03-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='flag_novelty',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
