# Generated by Django 4.0.2 on 2022-03-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_dish_flag_novelty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='flag_novelty',
            field=models.BooleanField(blank=True),
        ),
    ]
