# Generated by Django 4.0.2 on 2022-03-03 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_dish_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafe.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_weight',
            field=models.PositiveIntegerField(verbose_name='Вес (в граммах)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='flag_novelty',
            field=models.BooleanField(blank=True, verbose_name='Новинка'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='flag_popular',
            field=models.BooleanField(blank=True, verbose_name='Популярное'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='flag_promotion',
            field=models.BooleanField(blank=True, verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(null=True, upload_to='images/dish/', verbose_name='Фото блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='product',
            field=models.ManyToManyField(to='cafe.Product', verbose_name='Состав продуктов'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(max_length=75, unique=True, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
