# Generated by Django 4.0.2 on 2022-03-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_alter_category_id_alter_dish_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='flag_available',
            field=models.BooleanField(blank=True, default=True, verbose_name='Доступно ли блюдо к продаже'),
        ),
        migrations.AddField(
            model_name='dish',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер скидки'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='product',
            field=models.ManyToManyField(to='cafe.Product', verbose_name='Используемые продукты'),
        ),
    ]
