# Generated by Django 4.0.2 on 2022-03-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_dish_flag_available_dish_stock_alter_dish_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
    ]
