# Generated by Django 4.0.2 on 2022-03-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0012_alter_product_options_alter_dish_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
    ]
