# Generated by Django 4.0.2 on 2022-03-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0014_alter_dish_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('title',)},
        ),
    ]
