# Generated by Django 4.0.2 on 2022-03-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0015_alter_dish_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(null=True, upload_to='images/dish/', verbose_name='Фото блюда'),
        ),
    ]
